### ISSUE TITLE
5V dc source

### ISSUE THREAD

**Issue by RobiDobo** [WerkAG/ESP32Radio_PCB_v3.1#5]
Can I do this without having a 5v dc source? Other esp32 dev boards have the pin for 5V but I dont see it on this one. Can I use a normal esp32 and power it externally? The design looks really good too, sorry if this is offtopic i'm a beginner.

**Comment by WerkAG** [comment]
The ESP32 board used on this project also have a 5V input pin. You will need a 5V DC source, that you can connect to the 5V power input on the PCB.
Thanks.

**Comment by RobiDobo** [comment]
Thanks much.

**Comment by RobiDobo** [comment]
Also, can you please tell me if I can use a PAM8403 with a built in potentiometer?

**Comment by WerkAG** [comment]
If you understood what is said about the common ground issue and know how to correctly connect the PAM8403 with a built in potentiometer, I think you can. I just can comment on this project as it is, any changes you need to try by yourself.

Any 5V power supply with at least 1Amp should work.

**Comment by RobiDobo** [comment]
I think I understand, looking at a couple of projects some use audio transformers to eliminate the noise, while you use capacitors. I will try this, thank you a lot for the files and help.

**Comment by WerkAG** [comment]
The trick is not the capacitor, but not mix the GND of the general circuit with the Analog GND (GBUF) from the VS1053.

**Comment by RobiDobo** [comment]
That makes sense! Thank you for clarification. I can't help but notice in the part list it says 0806 SMD resistors, but on the internet i could only find 0805 SMD. What's the deal there?

**Comment by WerkAG** [comment]
You are helping :-) The resistors are 0805, it was a typo error. Already corrected, thank you.
