### ISSUE TITLE
Transistor

### ISSUE THREAD

**Issue by RobiDobo** [WerkAG/ESP32Radio_PCB_v3.1#6]
I can't find this transistor, can you please give an alternative?

**Comment by WerkAG** [comment]
Have you "googled" for it? It is available at almost all of the great distributors of electronic parts, such as Farnell, Digikey, TME, Mouser and many others.
Possibly there are many equivalents too, but at moment I don't remember of any to mention.

**Comment by RobiDobo** [comment]
i did but those distributors ship very expensively so I'd like to find something locally so that it doesnt cost a ton

**Comment by RobiDobo** [comment]
Thank you anyway, if you remember something let me know please

**Comment by WerkAG** [comment]
Try AliExpress...
